### ISSUE TITLE
Updating title dynamically?

### ISSUE THREAD

**Issue by rodydavis** [nuc134r/tab_switcher#1]
Love the library! Curious how to change the title for the current tab on the fly?

**Comment by nuc134r** [comment]
Thanks. 

For now there is no way of doing that. Also, titles and subtitles were supposed to become widgets in the future. I think when they become widgets it will be easier to implement such a feature. 

Active development of this library has stopped as an MVP based on it didn't really get past prototypes. But I would happily accept PRs and I'm hoping to start working on something that involves this UI paradigm in future.

**Comment by nuc134r** [comment]
> For now there is no way of doing that

...using stock widgets. You can actually subclass `TabSwitcherTab` with title changing feature and supply your own set of widget builder methods in `TabSwitcherWidget` which would support that by listening to custom streams from your `TabSwitcherTab`. That's would require some work but is achievable. This lib is actually very customizable and only provides root mechanism, just like `Scaffold` and a set of basic views which can be overridden using [builders](https://github.com/nuc134r/tab_switcher/blob/07d091c84ea9c756b2405d36377d42cd45e0a2a1/lib/tab_switcher_impl.dart#L15-L18).

**Comment by rodydavis** [comment]
Yeah I opened an issue because I started a fork. I also have added theme options too. I'll make some PRs soon.

I have an app with a lot of screens and needing multitasking and this worked really good.

I just added the project as a submodule instead of pub.dev for faster iteration.

But wanted to say thank you and great job on it!

**Comment by nuc134r** [comment]
Nice to hear it helps. Good luck and thank you!

**Comment by rodydavis** [comment]
Here is the PR! Feel free to close:

https://github.com/nuc134r/tab_switcher/pull/2

Here is an online demo:

https://hymns-for-worship.github.io/tab_switcher/

**Comment by rodydavis** [comment]
<img width="1012" alt="Screen Shot 2022-09-13 at 12 12 39 AM" src="https://user-images.githubusercontent.com/31253215/189838719-a3824308-a150-4837-bf64-0cd145efafbb.png">
<img width="1012" alt="Screen Shot 2022-09-13 at 12 12 32 AM" src="https://user-images.githubusercontent.com/31253215/189838725-c65c905d-fa12-47ad-8ea5-d876af12efff.png">
